alias dash="open dash://$1"
alias gst='git status'
alias gup="git pull --rebase"
alias gp="git push"
alias gap="git add -p"
alias duet='git duet --global'
alias solo='git solo --global'
alias be='bundle exec'
alias bx='be'
alias show="ps auxww | grep -v grep | grep "
alias vim=nvim
alias fixow='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo "Open With has been rebuilt, Finder will relaunch"'
alias flushdns='sudo discoveryutil udnsflushcaches'
