export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export GOPATH=$HOME/Projects/Go
export PATH=$PATH:$GOPATH/bin
export MONO_GAC_PREFIX="/usr/local/gac"
export PS1="\u@\h:\w$ "
export GIT_EDITOR="subl --wait --new-window"
export CLICOLOR=1
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
alias ls="ls -GFh"
