#!/usr/bin/env bash

export SCM_CHECK=true
export BASH_IT=$HOME/.bash_it
export BASH_IT_THEME='ralch'
source $BASH_IT/bash_it.sh

export EDITOR='vim'
export GIT_EDITOR='vim'

export GIT_DUET_GLOBAL=true
export GIT_DUET_ROTATE_AUTHOR=true

unset MAILCHECK

export JAVA_HOME=/usr/libexec/java_home
export USR_SBIN=/usr/local/sbin
export USR_BIN=$HOME/.bin
export GOPATH=$HOME/workspace/go
export GOBIN=$GOPATH/bin
export GOSRC=$GOPATH/src
export NVIM_TUI_ENABLE_TRUE_COLOR=true

alias ls='ls -G'

_direnv_hook() {
  eval "$(direnv export bash)";
};
if ! [[ "$PROMPT_COMMAND" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook;$PROMPT_COMMAND";
fi

export PATH=$PATH:$GOBIN:$USR_BIN:$USR_SBIN

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
[[ -s "$HOME/.dnx/dnvm/dnvm.sh" ]] && source "$HOME/.dnx/dnvm/dnvm.sh" # Load dnvm
