#!/usr/bin/env bash

export SCM_CHECK=true
export BASH_IT=$HOME/.bash_it
export BASH_IT_THEME='ralch'
source $BASH_IT/bash_it.sh

export EDITOR='vim'
export GIT_EDITOR='vim'

export GIT_DUET_GLOBAL=true
export GIT_DUET_ROTATE_AUTHOR=1

unset MAILCHECK

export JAVA_HOME=/usr/libexec/java_home
export GOPATH=$HOME/workspace/go
export GOBIN=$GOPATH/bin
export GOSRC=$GOPATH/src

alias ls='ls -G'

_direnv_hook() {
  eval "$(direnv export bash)";
};
if ! [[ "$PROMPT_COMMAND" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook;$PROMPT_COMMAND";
fi

export PATH=/usr/local/sbin:$PATH:$GOBIN
